# Generated by Django 3.2.16 on 2022-12-01 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название локации')),
                ('description_short', models.CharField(blank=True, max_length=600, verbose_name='Краткое описание')),
                ('description_long', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('lng', models.FloatField(blank=True, verbose_name='Долгота')),
                ('lat', models.FloatField(blank=True, verbose_name='Широта')),
                ('detailsUrl', models.CharField(max_length=1024, verbose_name='Временная ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
        ),
    ]
