# Generated by Django 3.2.16 on 2022-12-02 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_place_detailsurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place'),
        ),
    ]
