# Generated by Django 3.2.16 on 2022-12-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20221207_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='place',
        ),
    ]
