# Generated by Django 5.2.3 on 2025-07-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_image_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['title']},
        ),
    ]
